#! /usr/bin/env bash

(
  cd $(dirname $0)
  cat *.md |  grep -n -i -e TODO
  find src/main/python \
       -maxdepth 2 \
       -name "*.py" -o -name "*.html" \
       -type f | \
      xargs grep -n -i -e TODO
)
