-- 
-- create table customer_search_index
-- (
--  id INTEGER AUTO_INCREMENT PRIMARY KEY,
--  customer_id INTEGER NOT NULL,
--  title VARCHAR(1024),
--  body VARCHAR(4000) ,
--  FULLTEXT(title, body),
--  constraint FK_customer_search_index foreign key(customer_id) references customer_customer(id) 
-- ) ENGINE=MyIsam;

